"""empty message

Revision ID: 25bee6e95ef3
Revises: 3e7cce46f6ac
Create Date: 2015-01-23 19:56:25.724207

"""

# revision identifiers, used by Alembic.
revision = '25bee6e95ef3'
down_revision = '3e7cce46f6ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
