"""empty message

Revision ID: 3e7cce46f6ac
Revises: 59b527442f5f
Create Date: 2015-01-23 19:56:16.159985

"""

# revision identifiers, used by Alembic.
revision = '3e7cce46f6ac'
down_revision = '59b527442f5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
