"""empty message

Revision ID: 7eb56dfd2e4
Revises: 25bee6e95ef3
Create Date: 2015-01-24 01:38:25.883655

"""

# revision identifiers, used by Alembic.
revision = '7eb56dfd2e4'
down_revision = '25bee6e95ef3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
